-- ============================================
-- ProgressBridge - Corrected Database Schema
-- Compatible with existing BIGINT IDs
-- ============================================

-- Enable extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS postgis;


-- ============================================
-- 1. USERS
-- ============================================

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    role TEXT NOT NULL CHECK (
        role IN ('FIELD_ENGINEER', 'EXECUTIVE_ENGINEER')
    ),
    employee_id TEXT UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);


-- ============================================
-- 2. REPORTS
-- ============================================

CREATE TABLE IF NOT EXISTS reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    project_id BIGINT NOT NULL
        REFERENCES projects(id) ON DELETE CASCADE,

    activity_id BIGINT
        REFERENCES activities(id) ON DELETE SET NULL,

    submitted_by BIGINT
        REFERENCES users(id) ON DELETE SET NULL,

    report_date DATE NOT NULL,
    claimed_progress DOUBLE PRECISION NOT NULL,
    narrative TEXT,

    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,

    photo_timestamp TIMESTAMPTZ,
    device_signature TEXT,

    ai_confidence DOUBLE PRECISION,

    ai_recommended_activity BIGINT
        REFERENCES activities(id) ON DELETE SET NULL,

    created_at TIMESTAMPTZ DEFAULT NOW()
);


-- ============================================
-- 3. VERIFICATIONS
-- ============================================

CREATE TABLE IF NOT EXISTS verifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    report_id BIGINT NOT NULL
        REFERENCES reports(id) ON DELETE CASCADE,

    officer_id BIGINT
        REFERENCES users(id) ON DELETE SET NULL,

    decision TEXT NOT NULL
        CHECK (decision IN ('APPROVED', 'REJECTED', 'PENDING')),

    officer_feedback TEXT,
    sanction_order TEXT,

    verified_at TIMESTAMPTZ DEFAULT NOW()
);


-- ============================================
-- 4. AUDIT LEDGER
-- ============================================

CREATE TABLE IF NOT EXISTS audit_ledger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    report_id BIGINT
        REFERENCES reports(id) ON DELETE SET NULL,

    officer_emp_id TEXT,

    decision TEXT NOT NULL,

    previous_hash TEXT,
    current_hash TEXT NOT NULL,

    timestamp TIMESTAMPTZ DEFAULT NOW()
);


-- ============================================
-- SPATIAL COLUMNS
-- ============================================

ALTER TABLE projects
ADD COLUMN IF NOT EXISTS boundary_point
geometry(Point, 4326);

ALTER TABLE reports
ADD COLUMN IF NOT EXISTS report_point
geometry(Point, 4326);


-- ============================================
-- INDEXES
-- ============================================

CREATE INDEX IF NOT EXISTS idx_projects_boundary_point
ON projects USING GIST (boundary_point);

CREATE INDEX IF NOT EXISTS idx_reports_report_point
ON reports USING GIST (report_point);

CREATE INDEX IF NOT EXISTS idx_activities_project_id
ON activities(project_id);

CREATE INDEX IF NOT EXISTS idx_reports_project_id
ON reports(project_id);

CREATE INDEX IF NOT EXISTS idx_reports_activity_id
ON reports(activity_id);

CREATE INDEX IF NOT EXISTS idx_verifications_report_id
ON verifications(report_id);

CREATE INDEX IF NOT EXISTS idx_audit_report_id
ON audit_ledger(report_id);
-- ============================================
-- ============================================
-- SEED DATA
-- 6 infrastructure projects + 36 activities
-- ============================================

INSERT INTO projects
(project_name, latitude, longitude, planned_progress, actual_progress)
VALUES
('Mumbai Water Pipeline', 19.0760, 72.8777, 45, 40),
('Delhi-NCR Expressway', 28.6139, 77.2090, 70, 66),
('Bengaluru Metro Corridor', 12.9716, 77.5946, 55, 50),
('Hyderabad Riverfront Development', 17.3850, 78.4867, 40, 35),
('Chennai Coastal Drainage Upgrade', 13.0827, 80.2707, 60, 57),
('Pune Smart City Road Project', 18.5204, 73.8567, 50, 45);

-- Activities for the seeded projects
INSERT INTO activities
(project_id, activity_name, discipline, status)
VALUES
(2, 'Tunnel Excavation', 'Civil', 'In Progress'),
(2, 'Station Foundation Work', 'Civil', 'Completed'),
(2, 'Track Installation', 'Civil', 'Not Started'),
(2, 'Electrical Cabling', 'Electrical', 'In Progress'),
(2, 'Ventilation System Installation', 'Mechanical', 'Not Started'),
(2, 'Water Drainage Installation', 'Water Supply', 'In Progress'),

(3, 'Pipeline Trenching', 'Civil', 'Completed'),
(3, 'Main Pipeline Installation', 'Water Supply', 'In Progress'),
(3, 'Pipeline Joint Testing', 'Water Supply', 'Not Started'),
(3, 'Pump Installation', 'Mechanical', 'Not Started'),
(3, 'Electrical Control Panel Installation', 'Electrical', 'In Progress'),
(3, 'Road Restoration', 'Civil', 'Not Started'),

(4, 'Earthwork and Excavation', 'Civil', 'Completed'),
(4, 'Highway Pavement Construction', 'Civil', 'In Progress'),
(4, 'Drainage System Construction', 'Water Supply', 'In Progress'),
(4, 'Street Lighting Installation', 'Electrical', 'Not Started'),
(4, 'Traffic Signal Installation', 'Electrical', 'Not Started'),
(4, 'Roadside Mechanical Equipment', 'Mechanical', 'Not Started'),

(5, 'Viaduct Construction', 'Civil', 'In Progress'),
(5, 'Station Structural Work', 'Civil', 'In Progress'),
(5, 'Rail Track Installation', 'Civil', 'Not Started'),
(5, 'Power Supply Installation', 'Electrical', 'In Progress'),
(5, 'Escalator Installation', 'Mechanical', 'Not Started'),
(5, 'Water Supply and Drainage', 'Water Supply', 'Not Started'),

(6, 'Riverbank Civil Works', 'Civil', 'In Progress'),
(6, 'Storm Water Drainage', 'Water Supply', 'In Progress'),
(6, 'Electrical Lighting Installation', 'Electrical', 'Not Started'),
(6, 'Water Pump Installation', 'Mechanical', 'Not Started'),
(6, 'Walkway Construction', 'Civil', 'Not Started'),
(6, 'Water Pipeline Connection', 'Water Supply', 'Not Started'),

(6, 'Drain Excavation', 'Civil', 'Completed'),
(6, 'Drainage Pipeline Installation', 'Water Supply', 'In Progress'),
(6, 'Pump Station Construction', 'Mechanical', 'In Progress'),
(6, 'Electrical Pump Connections', 'Electrical', 'Not Started'),
(6, 'Flood Control Structure', 'Civil', 'Not Started'),
(6, 'Water Flow Testing', 'Water Supply', 'Not Started');
