-- ============================================
-- ProgressBridge - Corrected Database Schema
-- Compatible with existing BIGINT IDs
-- ============================================

-- Enable extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS postgis;


-- ============================================
-- 1. USERS
-- ============================================

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    role TEXT NOT NULL CHECK (
        role IN ('FIELD_ENGINEER', 'EXECUTIVE_ENGINEER')
    ),
    employee_id TEXT UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);


-- ============================================
-- 2. REPORTS
-- ============================================

CREATE TABLE IF NOT EXISTS reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    project_id BIGINT NOT NULL
        REFERENCES projects(id) ON DELETE CASCADE,

    activity_id BIGINT
        REFERENCES activities(id) ON DELETE SET NULL,

    submitted_by BIGINT
        REFERENCES users(id) ON DELETE SET NULL,

    report_date DATE NOT NULL,
    claimed_progress DOUBLE PRECISION NOT NULL,
    narrative TEXT,

    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,

    photo_timestamp TIMESTAMPTZ,
    device_signature TEXT,

    ai_confidence DOUBLE PRECISION,

    ai_recommended_activity BIGINT
        REFERENCES activities(id) ON DELETE SET NULL,

    created_at TIMESTAMPTZ DEFAULT NOW()
);


-- ============================================
-- 3. VERIFICATIONS
-- ============================================

CREATE TABLE IF NOT EXISTS verifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    report_id BIGINT NOT NULL
        REFERENCES reports(id) ON DELETE CASCADE,

    officer_id BIGINT
        REFERENCES users(id) ON DELETE SET NULL,

    decision TEXT NOT NULL
        CHECK (decision IN ('APPROVED', 'REJECTED', 'PENDING')),

    officer_feedback TEXT,
    sanction_order TEXT,

    verified_at TIMESTAMPTZ DEFAULT NOW()
);


-- ============================================
-- 4. AUDIT LEDGER
-- ============================================

CREATE TABLE IF NOT EXISTS audit_ledger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    report_id BIGINT
        REFERENCES reports(id) ON DELETE SET NULL,

    officer_emp_id TEXT,

    decision TEXT NOT NULL,

    previous_hash TEXT,
    current_hash TEXT NOT NULL,

    timestamp TIMESTAMPTZ DEFAULT NOW()
);


-- ============================================
-- SPATIAL COLUMNS
-- ============================================

ALTER TABLE projects
ADD COLUMN IF NOT EXISTS boundary_point
geometry(Point, 4326);

ALTER TABLE reports
ADD COLUMN IF NOT EXISTS report_point
geometry(Point, 4326);


-- ============================================
-- INDEXES
-- ============================================

CREATE INDEX IF NOT EXISTS idx_projects_boundary_point
ON projects USING GIST (boundary_point);

CREATE INDEX IF NOT EXISTS idx_reports_report_point
ON reports USING GIST (report_point);

CREATE INDEX IF NOT EXISTS idx_activities_project_id
ON activities(project_id);

CREATE INDEX IF NOT EXISTS idx_reports_project_id
ON reports(project_id);

CREATE INDEX IF NOT EXISTS idx_reports_activity_id
ON reports(activity_id);

CREATE INDEX IF NOT EXISTS idx_verifications_report_id
ON verifications(report_id);

CREATE INDEX IF NOT EXISTS idx_audit_report_id
ON audit_ledger(report_id);
